tst

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,17 +1,18 @@
 #!/usr/bin/env ruby
-#$:.unshift File.expand_path("../../lib", __FILE__)
-#require "language_pack"
+$:.unshift File.expand_path("../../lib", __FILE__)
+puts "unshift this!"
+require "language_pack"
 
 puts "looking for the goodies."
-# if pack = LanguagePack.detect(ARGV.first)
-#   puts "pack name is #{pack.name}"
-#   # if [ -f $1/rhoconnect ]; then
-#   #     echo "found rhoconnect" && exit 0
-#   #   else
-#   #     echo "rhoconect not found" && exit 1
-#   #   fi
-#   exit 0
-# else
-#   puts "no"
-#   exit 1
-# end
+if pack = LanguagePack.detect(ARGV.first)
+  puts "pack name is #{pack.name}"
+  # if [ -f $1/rhoconnect ]; then
+  #     echo "found rhoconnect" && exit 0
+  #   else
+  #     echo "rhoconect not found" && exit 1
+  #   fi
+  exit 0
+else
+  puts "no"
+  exit 1
+end
