tst

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,19 +1,19 @@
 #!/usr/bin/env ruby
 puts "whodat"
-# $:.unshift File.expand_path("../../lib", __FILE__)
-# puts "unshift this!"
-# require "language_pack"
-# 
-# puts "looking for the goodies."
-# if pack = LanguagePack.detect(ARGV.first)
-#   puts "pack name is #{pack.name}"
-#   # if [ -f $1/rhoconnect ]; then
-#   #     echo "found rhoconnect" && exit 0
-#   #   else
-#   #     echo "rhoconect not found" && exit 1
-#   #   fi
-#   exit 0
-# else
-#   puts "no"
-#   exit 1
-# end
+$:.unshift File.expand_path("../../lib", __FILE__)
+puts "unshift this!"
+require "language_pack"
+
+puts "looking for the goodies."
+if pack = LanguagePack.detect(ARGV.first)
+  puts "pack name is #{pack.name}"
+  # if [ -f $1/rhoconnect ]; then
+  #     echo "found rhoconnect" && exit 0
+  #   else
+  #     echo "rhoconect not found" && exit 1
+  #   fi
+  exit 0
+else
+  puts "no"
+  exit 1
+end
